### ISSUE TITLE
Figures/Tables checklist

### ISSUE THREAD

**Issue by gwenchee** [arfc/2019-ddca-journal-article#19]
Figures:
- [x] Text on figures should be generously, readably sized.
- [x] Lines and symbols should be sized for generous readability as well ( and arranged so that the reader can, say, see the difference between two lines which are near one another.)
- [x] All figures need and deserve excellent pixel resolution (they should not be grainy). 
- [x] All figures need and deserve all of their axes to be labeled, with units.
- [x] All legends should be clear, with units. 
- [x] All figures should have captions, with clear sentences and citations of their source.
- [x] Caption location at bottom of figure

Tables: 
- [x] Tables need a title (or brief caption)
- [x] cite the source of  tables that are reproduced from elsewhere
- [x] Text should be generously, readably sized
- [x] All values with units should make those units clear
- [x] Numbers should line up at the decimal
- [x] Should not be grainy. 
- [x] If two tables are adjacent, they should be of the same font size (so be careful of your screen-shotting). 
- [x] Caption location at top of table
